# Generated by Django 2.2.12 on 2022-04-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20220421_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_data',
            new_name='post_date',
        ),
    ]
