# Generated by Django 2.2.12 on 2022-03-27 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_bet', models.IntegerField()),
                ('current_bet', models.IntegerField()),
                ('bet_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoper', to=settings.AUTH_USER_MODEL)),
                ('bet_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='auctions.Auction')),
            ],
        ),
    ]
