# Generated by Django 2.2.12 on 2022-03-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='photo',
            field=models.BinaryField(default=None, max_length=1024),
        ),
        migrations.AddField(
            model_name='auction',
            name='pub_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
