# Generated by Django 2.2.12 on 2022-03-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20220327_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='photo',
        ),
    ]
