# Generated by Django 2.2.12 on 2022-03-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_auction_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='pub_data',
        ),
    ]
