# Generated by Django 2.2.12 on 2022-03-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auction_pub_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.TextField(default='SOME DESCRIOTION'),
        ),
        migrations.AddField(
            model_name='auction',
            name='photo',
            field=models.ImageField(default='SOME FILE', max_length=1024, upload_to=''),
        ),
    ]
