# Generated by Django 2.2.12 on 2022-03-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20220328_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='com_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
