# Generated by Django 2.2.12 on 2022-03-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_comment_com_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bet',
            name='current_bet',
            field=models.IntegerField(default=models.IntegerField()),
        ),
    ]
