# Generated by Django 2.2.12 on 2022-03-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20220329_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='current_bet',
            field=models.FloatField(),
        ),
    ]
