# Generated by Django 2.2.12 on 2022-03-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='follow',
            field=models.BooleanField(default=False),
        ),
    ]
