# Generated by Django 2.2.12 on 2022-03-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_watchlist_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='follow',
            field=models.BooleanField(default=False, help_text='Add to WatchList'),
        ),
    ]
